name: Pull From Upstream

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install moban
        pip install xattr

    - name: Sync GitHub's master template repository of templates
      run: .github/scripts/sync-github.sh

    - name: Run moban then lint templates for white space
      run: |
        moban
        .github/scripts/check-whitespace.sh

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Sync Templates with Github
        title: Sync Templates with Github
        branch: sync_github
        base: master
